* The brown-paper-bag bug release * debian/postinst:   - only force-reload DBus if it's already started (Closes: #517395),     I had already fixed this in debian/postrm (see -2).
git-svn-id: svn://svn.debian.org/svn/python-apps/packages/wicd/trunk@2494 31130ce1-1128-498b-8474-bfd1e18f06ab

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -24,10 +24,15 @@ case "$1" in
     		addgroup --quiet --system netdev
     	fi
         if [ -x "/etc/init.d/dbus" ]; then
-            if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
-                invoke-rc.d dbus force-reload || exit $?
-            else
-                /etc/init.d/dbus force-reload || exit $?
+            # Check if DBus has started, otherwise this fails on
+            # certain environments (chroots, for example). See
+            # #514778 #517395
+            if [ -n "$DBUS_SESSION_BUS_ADDRESS" ]; then
+                if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
+                    invoke-rc.d dbus force-reload || exit $?
+                else
+                    /etc/init.d/dbus force-reload || exit $?
+                fi
             fi
         fi
     ;;
